setwd("~/MartynasLib/Universitetas/4 kursas/8_semestras/praktika/mano_r")

library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(DT)
library(plotly)
library(ape)
library(readxl)
library(writexl)
library(tidyr)
library(dplyr)
library(vegan)
library(phyloseq)
library(phytools)
library(ggtree)
library(ggdendro)

source("modules/upload.r")
source("modules/filter.r")
source("modules/metadataFilter.r")
source("modules/amplicon.r")

source("ui.r")
source("server.r")

shinyApp(ui, server)